[workspace]
resolver = "2"
members = [
    "crates/airs-mcp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["rstlix0x0 <rstlix.dev@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rstlix0x0/airs"
rust-version = "1.88.0"
