[workspace]
resolver = "2"
members = [
    "crates/airs-mcp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["rstlix0x0 <rstlix.dev@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rstlix0x0/airs"
rust-version = "1.84.0"

[workspace.dependencies]
serde_json = { version = "~1.0" }
serde = { version = "~1.0", features = ["derive"] }
tokio = { version = "~1", features = ["full"] }
tokio-util = { version = "~0.7" }
tokio-test = { version = "~0.6" }
futures = { version = "~0.3" }
dashmap = { version = "~6.1" }
thiserror = { version = "~2.0" }
proptest = { version = "~1.0" }
tracing = { version = "~0.1" }
tracing-subscriber = { version = "~0.3" }
uuid = { version = "~1.17", features = ["v4", "serde"] }