[workspace]
resolver = "2"
members = [
    "crates/airs-mcp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["rstlix0x0 <rstlix.dev@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rstlix0x0/airs"
rust-version = "1.84.0"

[workspace.dependencies]
# Core Serialization & Async Runtime
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tokio-test = "0.6"
futures = "0.3"

# Concurrent Collections & Utilities
dashmap = "6.1"
uuid = { version = "1.17", features = ["v4", "serde"] }

# Error Handling
thiserror = "2.0"

# Observability
tracing = "0.1"
tracing-subscriber = "0.3"

# Testing
proptest = "1.0"

# JSON-RPC Foundation Requirements (MINIMAL)
bytes = "1.8"                     # Efficient byte handling for message processing
criterion = "0.5"                 # Benchmarking for performance validation