[workspace]
resolver = "2"
members = [
    "crates/airs-mcp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["rstlix0x0 <rstlix.dev@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rstlix0x0/airs"
rust-version = "1.84.0"

[workspace.dependencies]
serde_json = { version = "~1.0" }
serde = { version = "~1.0", features = ["derive"] }
tokio = { version = "~1", features = ["full"] }
thiserror = { version = "~2.0" }