# Local Development Overrides
# This file is for individual developer customization
# It should be added to .gitignore and not committed to version control

[server]
name = "local-airs-mcp-fs"

[security.filesystem]
# Local developer paths
allowed_paths = [
    "/**/*",  # Full access for local development
    "/Users/*/projects/**/*",  # macOS user projects
    "/home/*/projects/**/*",   # Linux user projects
]

[security.operations]
# Very permissive for local development
write_requires_policy = false
delete_requires_explicit_allow = false

[binary]
# Smaller limits for faster local testing
max_file_size = 26214400  # 25MB

# Local development policies
[security.policies.local_workspace]
patterns = ["**/*"]
operations = ["read", "write", "delete", "list", "create_dir", "move", "copy"]
risk_level = "low"
description = "Local development - full access to all files"
