# Staging Environment Configuration
# Production-like settings with some flexibility for testing

[security.filesystem]
# Staging paths - more restrictive than dev, less than production
allowed_paths = [
    "/staging/data/**/*",
    "/staging/workspace/**/*", 
    "/app/test/**/*",
    "~/staging-workspace/**/*",
]

denied_paths = [
    # Critical system paths
    "/etc/**",
    "/root/**",
    "/boot/**",
    
    # Secrets and sensitive data
    "**/.ssh/**",
    "**/secrets/**", 
    "**/credentials/**",
    
    # Production data isolation
    "/app/production/**",
    "/var/lib/production/**",
]

[security.operations]
# Moderate security for staging
write_requires_policy = true
delete_requires_explicit_allow = false  # Allow deletions for test cleanup

[binary]  
# Staging file size limits
max_file_size = 157286400  # 150MB for staging tests

# Staging-specific policies
[security.policies.staging_data]
patterns = [
    "/staging/data/**/*",
    "/app/test/**/*.{json,xml,csv}",
]
operations = ["read", "write", "delete"]
risk_level = "medium"
description = "Staging test data - full access for testing"

[security.policies.test_artifacts]
patterns = [
    "/staging/workspace/**/*.{log,tmp,test}",
    "**/test-results/**",
    "**/coverage/**",
]
operations = ["read", "write", "delete"]
risk_level = "low"
description = "Test artifacts and logs - full cleanup allowed"

[security.policies.staging_config]
patterns = [
    "/staging/config/**/*.{toml,yaml,json}",
]
operations = ["read", "write"]
risk_level = "medium"
description = "Staging configuration - controlled modification"

[security.policies.mock_data]
patterns = [
    "**/mock/**/*",
    "**/fixtures/**/*",
    "**/sample-data/**/*",
]
operations = ["read", "write"]
risk_level = "low"
description = "Mock and sample data - safe for testing"
