[package]
name = "airs-mcp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Model Context Protocol implementation with JSON-RPC 2.0 foundation"
keywords = ["mcp", "jsonrpc", "protocol", "rpc"]
categories = ["network-programming", "api-bindings"]

[dependencies]
# Core serialization for JSON-RPC messages (current implementation needs)
serde.workspace = true
serde_json.workspace = true

# Future dependencies (commented out until actually needed)
# tokio.workspace = true
# futures.workspace = true
# dashmap.workspace = true
# thiserror.workspace = true
# uuid.workspace = true
# bytes.workspace = true
# tokio-util.workspace = true
# tracing.workspace = true

[dev-dependencies]
# Only include what we actually need for current tests
# tokio-test.workspace = true
# proptest.workspace = true
# tracing-subscriber.workspace = true
# criterion.workspace = true
