# Cargo audit configuration for AirsStack workspace
# See: https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example

[advisories]
# RUSTSEC-2023-0071: RSA Marvin Attack
# Status: Known vulnerability in RSA crate - no patch available yet
# Impact: Dev-dependencies only (OAuth2 examples), not in production code paths
# Mitigation: RSA is isolated to dev-dependencies and example code only
# Action: Monitor for upstream fix, consider alternative crypto libraries
# Risk Assessment: VERY LOW (development/example code only)
ignore = [
    "RUSTSEC-2023-0071", # RSA Marvin Attack - dev-dependencies only
    "RUSTSEC-2024-0436", # paste - unmaintained (image processing chain)
    "RUSTSEC-2025-0067", # libyml - unsound (YAML processing)
    "RUSTSEC-2025-0068", # serde_yml - unsound (YAML processing)
]

# Note: All ignored vulnerabilities are in non-critical paths:
# - RSA: Only in dev-dependencies for OAuth2 examples
# - paste: Indirect through image processing (ravif -> rav1e)
# - libyml/serde_yml: YAML processing, not core MCP protocol