# Base AIRS MCP-FS Configuration
# This file contains shared configuration that applies to all environments
# Environment-specific files (development.toml, production.toml, etc.) will override these values

[server]
name = "airs-mcp-fs"
version = "0.1.0"

[binary]
# Maximum file size in bytes (100MB default)
max_file_size = 104857600
enable_image_processing = true
enable_pdf_processing = true

[security.filesystem]
# Base allowed paths - can be overridden per environment
allowed_paths = [
    "~/projects/**/*",
    "~/Documents/**/*.{md,txt,rst}",
]

# Always denied paths across all environments
denied_paths = [
    "**/.git/**",
    "**/.env*",
    "~/.*/**",         # Hidden directories
    "**/id_rsa*",      # SSH keys
    "**/credentials*", # Credential files
    "**/secrets*",     # Secret files
    "/etc/**",         # System configuration
    "/var/log/**",     # System logs
]

[security.operations]
read_allowed = true
create_dir_allowed = true
# write_requires_policy and delete_requires_explicit_allow will be set per environment

# Default security policies for common file types
[security.policies.source_code]
patterns = [
    "**/*.{rs,py,js,ts,jsx,tsx}",
    "**/*.{c,cpp,h,hpp}",
    "**/*.{java,kt,scala}",
    "**/*.{go,rb,php}",
]
operations = ["read", "write"]
risk_level = "low"
description = "Source code files - safe for development"

[security.policies.documentation]
patterns = [
    "**/*.{md,txt,rst}",
    "**/README*",
    "**/CHANGELOG*",
    "**/LICENSE*",
    "**/*.adoc",
]
operations = ["read", "write"]
risk_level = "low"
description = "Documentation files - safe for editing"

[security.policies.config_files]
patterns = [
    "**/Cargo.toml",
    "**/*.{json,yaml,yml,toml}",
    "**/*.{xml,ini,conf}",
    "**/package.json",
]
operations = ["read", "write"]
risk_level = "medium"
description = "Configuration files - moderate risk"

[security.policies.build_artifacts]
patterns = [
    "**/target/**",
    "**/dist/**",
    "**/build/**",
    "**/node_modules/**",
    "**/*.{tmp,bak,log}",
]
operations = ["read", "delete"]
risk_level = "low"
description = "Build artifacts and temporary files - safe to clean"
