# Development Environment Configuration
# Permissive settings for local development and testing

[security.filesystem]
# More permissive paths for development
allowed_paths = [
    "/**/*",  # Allow access to most files for development
]

[security.operations]
# Permissive operations for development
write_requires_policy = false
delete_requires_explicit_allow = false

[security]
# Binary processing disabled for security across all environments
binary_processing_disabled = true
text_only_mode = true
max_file_size = 52428800  # 50MB for text files

# Additional development-specific policies
[security.policies.development_files]
patterns = [
    "**/*.{log,tmp,test}",
    "**/test/**",
    "**/tests/**",
    "**/__pycache__/**",
    "**/.pytest_cache/**",
]
operations = ["read", "write", "delete"]
risk_level = "low"
description = "Development and test files - full access allowed"

[security.policies.journals]
patterns = [
    "/Users/*/Documents/kaaljournal/**/*.md",
]
operations = ["read", "write"]
risk_level = "low"
description = "Journal files - full access allowed"

[security.policies.git_files]
patterns = [
    "**/.gitignore",
    "**/.gitattributes",
    "**/.github/**",
]
operations = ["read", "write"]
risk_level = "low"
description = "Git configuration files - safe in development"
